name: Build & Push Node.js 25 to OCI Image Registry

on:
  push:
    branches:
      - main
    paths:
      - "25/**/Dockerfile"
  pull_request:
    branches:
      - main
    paths:
      - "25/**/Dockerfile"

jobs:
  workdirs:
    uses: ./.github/workflows/specify-workdir.yaml
    with:
      base-dir: 25

  image:
    uses: ./.github/workflows/build.yaml
    needs: workdirs
    with:
      workdirs: ${{ needs.workdirs.outputs.workdirs-array }}
      images: |
        docker.io/hazmi35/node
        ghcr.io/hazmi35/node
    secrets:
      docker-hub-username: hazmi35
      docker-hub-access-token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      ghcr-username: ${{ github.repository_owner }}
      ghcr-access-token: ${{ secrets.GITHUB_TOKEN }}
